### ISSUE TITLE
Fatal errors with Bigred3 @ IU

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/app-fmriprep#16]
When running the app (master branch) on Bigred3 I found this error:
`FATAL:   Unable to handle docker://poldracklab/fmriprep:20.1.2 uri: while building SIF from layers: conveyor failed to get: Error writing blob: write /tmp/bundle-temp-688972288/oci-put-blob960920304: no space left on device`
or alternatively this error:
`FATAL:   Unable to handle docker://poldracklab/fmriprep:20.1.2 uri: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack layer: unpack entry: usr/lib/ants/WarpTensorImageMultiTransform: unpack to regular file: short write: write /tmp/rootfs-4f69c9e1-f8c5-11ea-836d-000101000008/usr/lib/ants/WarpTensorImageMultiTransform: cannot allocate memory`

**Comment by soichih** [comment]
It looks like the node that this job ran on ran out of /tmp.

I also noticed that Bigred3 is not using job specific TMPDIR. I see this in
env dump from a job.

TMPDIR=/tmp

It should look like this instead.

TMPDIR=/tmp/2111477.s1

I will ping the admin and see what they say. I don't know having job
specific TMPDIR would have prevented the /tmp from going out of disk, but I
need the admin to free up the space anyway. Can you try rerunning the job?

**Comment by giulia-berto** [comment]
I re-ran it, and got the following error:
`Traceback (most recent call last):
  File "/N/u/brlife/BigRed3/abcd-spec/hooks/slurm/bl2bids", line 228, in <module>
    link(src, dest+"_"+base)
  File "/N/u/brlife/BigRed3/abcd-spec/hooks/slurm/bl2bids", line 46, in link
    os.link(src, dest)
PermissionError: [Errno 1] Operation not permitted: '../5f60d26079a30bd423e9dcce/5eebda086438567c675dda10/output' -> 'bids/derivatives/5f60d26079a30bd423e9dcce/sub-101/dt-58cb22c8e13a50849b25882e.todo/sub-101_output'`

**Comment by soichih** [comment]
I think I've fixed the fmriprep SIF image issue, but I am not sure why you are seeing the permissionerror from bl2bids command. Can you try removing the bids directory? And rerun it again?

**Comment by giulia-berto** [comment]
Still the same error, both with BigRed3 and Carbonate. Maybe it has to do with r/w permissions of the freesurfer directory?

**Comment by francopestilli** [comment]
@giulia-berto do you have access to that directory?

**Comment by soichih** [comment]
I had to update to use hardlink instead of symlink for bl2bids to link between original brainlife input paths to bids paths. I did this to make C-PAC working on BLI've completely forgotten that hardlink can't handle directory even if it's on the same file system.

@shnizzedy What do you think will happen if I use hard link for regular files, but symlink for directories? Will C-PAC break then?

**Comment by shnizzedy** [comment]
I think that strategy would work for C-PAC. The issue with symlinks in C-PAC at the moment is that various nodes along the way check for files to exist, and that check fails for symlinks. For directories I don't think there should be any issue with symlinks since, as you mentioned, directories typically can't be hardlinked anyway.

**Comment by giulia-berto** [comment]
@francopestilli No, I don't have access to the scratch folder of BigRed3 `/N/dc2/scratch/brlife/br3-workflows/`.
@soichih It makes sense.

**Comment by soichih** [comment]
I've updated bl2bids to use symlink for directory paths, and I've released the update to carbonate and bigred3 resources. @giulia-berto Can you try rerunning your job?

**Comment by giulia-berto** [comment]
Thanks @soichih, it works now on BigRed3. I will close this issue.
